{{- if and .Values.storage.enabled .Values.storage.ingress .Values.storage.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supabase.fullname" . }}-storage
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.storage.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.storage.ingress.ingressClassName }}
  ingressClassName: {{ .Values.storage.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.storage.ingress.tls }}
  tls:
    {{- range .Values.storage.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.storage.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- else }}
            pathType: Prefix
            {{- end }}
            backend:
              service:
                name: {{ include "supabase.fullname" $ }}-storage
                port:
                  {{- if .backend.service.port.number }}
                  number: {{ .backend.service.port.number }}
                  {{- else }}
                  name: {{ .backend.service.port.name | default "http" }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
