{{- if and .Values.storage.enabled (and .Values.storage .Values.storage.podDisruptionBudget) .Values.storage.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "supabase.fullname" . }}-storage
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.storage.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.storage.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.storage.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.storage.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.storage.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
{{- end }}
