{{- if and .Values.studio.enabled (and .Values.studio .Values.studio.podDisruptionBudget) .Values.studio.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "supabase.fullname" . }}-studio
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: studio
  {{- with .Values.studio.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.studio.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.studio.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.studio.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.studio.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: studio
{{- end }}
