{{- if and .Values.auth.enabled (.Values.auth.ingressPerReplica).enabled }}
{{- $fullName := include "supabase.fullname" . }}
{{- $svcPort := (.Values.auth.service).port }}
{{- $replicas := (.Values.auth).replicaCount | default 1 }}
{{- range $i := until (int $replicas) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-auth-{{ $i }}
  labels:
    {{- include "supabase.labels" $ | nindent 4 }}
    app.kubernetes.io/component: auth
    statefulset.kubernetes.io/pod-name: {{ $fullName }}-auth-{{ $i }}
  {{- with ($.Values.auth.ingressPerReplica).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if ($.Values.auth.ingressPerReplica).ingressClassName }}
  ingressClassName: {{ ($.Values.auth.ingressPerReplica).ingressClassName }}
  {{- end }}
  {{- if ($.Values.auth.ingressPerReplica).tls }}
  tls:
    {{- range ($.Values.auth.ingressPerReplica).tls }}
    - hosts:
        {{- range .hosts }}
        - {{ printf "%s-%d.%s" $fullName $i . | quote }}
        {{- end }}
      secretName: {{ printf "%s-%d" .secretName $i }}
    {{- end }}
  {{- end }}
  rules:
    {{- range ($.Values.auth.ingressPerReplica).hosts }}
    - host: {{ printf "%s-%d.%s" $fullName $i .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}-auth-{{ $i }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
