{{- if and .Values.auth.enabled (.Values.thanos).enabled (.Values.auth.thanos.sidecar).enabled (.Values.auth.thanos.sidecar.ingress).enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supabase.fullname" . }}-auth-thanos-sidecar
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: thanos
  {{- with (.Values.auth.thanos.sidecar.ingress).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if (.Values.auth.thanos.sidecar.ingress).ingressClassName }}
  ingressClassName: {{ (.Values.auth.thanos.sidecar.ingress).ingressClassName }}
  {{- end }}
  {{- if (.Values.auth.thanos.sidecar.ingress).tls }}
  tls:
    {{- range (.Values.auth.thanos.sidecar.ingress).tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range (.Values.auth.thanos.sidecar.ingress).hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "supabase.fullname" $ }}-auth-thanos-sidecar
                port:
                  number: {{ ($.Values.auth.thanos.sidecar.service).port | default 10902 }}
          {{- end }}
    {{- end }}
{{- end }}
