{{- if and .Values.auth.enabled .Values.auth.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supabase.fullname" . }}-auth
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- with .Values.auth.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.auth.ingress.className }}
  ingressClassName: {{ .Values.auth.ingress.className }}
  {{- end }}
  {{- if .Values.auth.ingress.tls }}
  tls:
    {{- range .Values.auth.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.auth.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "supabase.fullname" $ }}-auth
                port:
                  number: {{ $.Values.auth.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
