{{- if and .Values.auth.enabled (and .Values.auth .Values.auth.podDisruptionBudget) .Values.auth.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "supabase.fullname" . }}-auth
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- with .Values.auth.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.auth.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.auth.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.auth.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.auth.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth
{{- end }}
