{{- if and .Values.auth.enabled .Values.auth.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "supabase.fullname" . }}-auth
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
    {{- with .Values.auth.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.auth.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth
  podMetricsEndpoints:
    {{- range .Values.auth.podMonitor.endpoints }}
    - port: {{ .port }}
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      {{- if .scheme }}
      scheme: {{ .scheme }}
      {{- end }}
      {{- if .scrapeTimeout }}
      scrapeTimeout: {{ .scrapeTimeout }}
      {{- end }}
      {{- if .honorLabels }}
      honorLabels: {{ .honorLabels }}
      {{- end }}
      {{- if .metricRelabelings }}
      metricRelabelings:
        {{- toYaml .metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .relabelings }}
      relabelings:
        {{- toYaml .relabelings | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if .Values.auth.podMonitor.jobLabel }}
  jobLabel: {{ .Values.auth.podMonitor.jobLabel }}
  {{- end }}
  {{- if .Values.auth.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml .Values.auth.podMonitor.podTargetLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.auth.podMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.auth.podMonitor.namespaceSelector | nindent 4 }}
  {{- end }}
  {{- if .Values.auth.podMonitor.sampleLimit }}
  sampleLimit: {{ .Values.auth.podMonitor.sampleLimit }}
  {{- end }}
  {{- if .Values.auth.podMonitor.targetLimit }}
  targetLimit: {{ .Values.auth.podMonitor.targetLimit }}
  {{- end }}
{{- end }}
