{{- if and .Values.auth.enabled (.Values.route).enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "supabase.fullname" . }}-auth
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- with (.Values.route).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if (.Values.route).host }}
  host: {{ (.Values.route).host }}
  {{- end }}
  {{- if (.Values.route).subdomain }}
  subdomain: {{ (.Values.route).subdomain }}
  {{- end }}
  path: {{ (.Values.auth.route).path | default "/auth/v1" }}
  to:
    kind: Service
    name: {{ include "supabase.fullname" . }}-auth
    weight: 100
  port:
    targetPort: {{ (.Values.auth.service).targetPort | default "http" }}
  {{- if (.Values.route).tls }}
  tls:
    {{- if ((.Values.route).tls).termination }}
    termination: {{ ((.Values.route).tls).termination }}
    {{- end }}
    {{- if ((.Values.route).tls).insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ ((.Values.route).tls).insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if ((.Values.route).tls).certificate }}
    certificate: |
{{ ((.Values.route).tls).certificate | indent 6 }}
    {{- end }}
    {{- if ((.Values.route).tls).key }}
    key: |
{{ ((.Values.route).tls).key | indent 6 }}
    {{- end }}
    {{- if ((.Values.route).tls).caCertificate }}
    caCertificate: |
{{ ((.Values.route).tls).caCertificate | indent 6 }}
    {{- end }}
    {{- if ((.Values.route).tls).destinationCACertificate }}
    destinationCACertificate: |
{{ ((.Values.route).tls).destinationCACertificate | indent 6 }}
    {{- end }}
  {{- end }}
  {{- if (.Values.route).wildcardPolicy }}
  wildcardPolicy: {{ (.Values.route).wildcardPolicy }}
  {{- end }}
{{- end }}
