{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-auth-secret
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- with (.Values.auth.secret).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ (.Values.auth.secret).type | default "Opaque" }}
{{- if (.Values.auth.secret).data }}
data:
  {{- range $key, $value := (.Values.auth.secret).data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- if (.Values.auth.secret).stringData }}
stringData:
  {{- range $key, $value := (.Values.auth.secret).stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if not (or (.Values.auth.secret).data (.Values.auth.secret).stringData) }}
stringData:
  database-url: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.legacySecret.db.username .Values.legacySecret.db.password (include "supabase.database.host" .) (.Values.legacySecret.db.port | toString) .Values.legacySecret.db.database }}
  jwt-secret: {{ .Values.legacySecret.jwt.secret | quote }}
  anon-key: {{ .Values.legacySecret.jwt.anonKey | quote }}
  service-key: {{ .Values.legacySecret.jwt.serviceKey | quote }}
{{- end }}
{{- end }}
