{{- if and .Values.realtime.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "supabase.fullname" . }}-realtime
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "supabase.fullname" . }}-realtime
subjects:
  - kind: ServiceAccount
    name: {{ include "supabase.realtime.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
