{{- if .Values.realtime.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-realtime
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
type: Opaque
{{- if .Values.realtime.secret }}
data:
  {{- range $key, $value := .Values.realtime.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- else }}
stringData:
  database-url: "postgresql://{{ .Values.legacySecret.db.username }}:{{ .Values.legacySecret.db.password }}@{{ include "supabase.database.host" . }}:5432/{{ .Values.legacySecret.db.database }}"
  jwt-secret: {{ .Values.legacySecret.jwt.secret | default "your-super-secret-jwt-token-with-at-least-32-characters-long" | quote }}
  anon-key: {{ .Values.legacySecret.jwt.anonKey | default "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE5NTczNDUyMDB9.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE" | quote }}
  service-key: {{ .Values.legacySecret.jwt.serviceKey | default "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2NDE3NjkyMDAsImV4cCI6MTk1NzM0NTIwMH0.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q" | quote }}
  db-host: {{ include "supabase.database.host" . | quote }}
  db-port: "5432"
  db-name: {{ .Values.legacySecret.db.database | default "postgres" | quote }}
  db-user: {{ .Values.legacySecret.db.username | default "postgres" | quote }}
  db-password: {{ .Values.legacySecret.db.password | default "postgres" | quote }}
  secret-key-base: {{ (.Values.legacySecret.realtime).secretKeyBase | default "UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq" | quote }}
  max-connections: {{ (.Values.realtime.config).maxConnections | default "100" | quote }}
  pool-size: {{ (.Values.realtime.config).poolSize | default "10" | quote }}
  port: {{ (.Values.realtime.config).port | default "4000" | quote }}
  hostname: {{ (.Values.realtime.config).hostname | default "localhost" | quote }}
  check-origin: {{ (.Values.realtime.config).checkOrigin | default "false" | quote }}
{{- end }}
{{- end }}
