{{- if .Values.analytics.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.analytics.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not (and .Values.analytics.autoscaling .Values.analytics.autoscaling.enabled) }}
  replicas: {{ .Values.analytics.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.analytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.analytics.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.analytics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.analytics.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.analytics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.analytics.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              {{- if .Values.db.enabled }}
              value: {{ include "supabase.db.fullname" . | quote }}
              {{- else }}
              value: {{ .Values.auth.environment.DB_HOST | quote }}
              {{- end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  {{- include "supabase.secrets.secretKeyRef" (dict "Values" .Values "service" "db" "field" "username" "context" .) | nindent 18 }}
            - name: DB_PORT
              value: "{{ .Values.analytics.environment.DB_PORT }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER"; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
      containers:
        - name: {{ include "supabase.analytics.name" $ }}
          securityContext:
            {{- toYaml .Values.analytics.securityContext | nindent 12 }}
          image: "{{ .Values.analytics.image.repository }}:{{ .Values.analytics.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.analytics.image.pullPolicy }}
          command: ["analytics"]
          env:
            {{- range $key, $value := .Values.analytics.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.db.enabled }}
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- end }}
          {{- if and .Values.global.csi .Values.global.csi.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.csi.secretName | default "" }}
          {{- else if .Values.global.defaultSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.defaultSecretName }}

          {{- else }}
          envFrom:
            - secretRef:
                name: {{ include "supabase.secretName" . }}

          {{- end }}
          {{- with .Values.analytics.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.analytics.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.analytics.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.analytics.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.analytics.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analytics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analytics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analytics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
