{{- if .Values.rest.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not (and .Values.rest.autoscaling .Values.rest.autoscaling.enabled) }}
  replicas: {{ .Values.rest.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.rest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.rest.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.rest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.rest.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.rest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.rest.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              {{- if .Values.db.enabled }}
              value: {{ include "supabase.db.fullname" . | quote }}
              {{- else }}
              value: {{ .Values.auth.environment.DB_HOST | quote }}
              {{- end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  {{- include "supabase.secrets.secretKeyRef" (dict "Values" .Values "service" "db" "field" "username" "context" .) | nindent 18 }}
            - name: DB_PORT
              value: "{{ .Values.rest.environment.DB_PORT }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER"; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
      containers:
        - name: {{ include "supabase.rest.name" $ }}
          securityContext:
            {{- toYaml .Values.rest.securityContext | nindent 12 }}
          image: "{{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rest.image.pullPolicy }}
          command: ["postgrest"]
          env:
            {{- range $key, $value := .Values.rest.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.db.enabled }}
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- end }}
          {{- if and .Values.global.csi .Values.global.csi.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.csi.secretName | default "" }}
          {{- else if .Values.global.defaultSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.defaultSecretName }}
          {{- else }}
          envFrom:
            - secretRef:
                name: {{ include "supabase.secretName" . }}
          {{- end }}
          {{- with .Values.rest.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rest.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.rest.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rest.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.rest.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
