{{- if and .Values.rest.enabled .Values.rest.podMonitor .Values.rest.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "supabase.fullname" . }}-rest
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
    {{- with .Values.rest.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rest.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.rest.podMonitor.jobLabel }}
  jobLabel: {{ .Values.rest.podMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rest
  podMetricsEndpoints:
    - port: {{ .Values.rest.podMonitor.port | default "http" }}
      {{- if .Values.rest.podMonitor.interval }}
      interval: {{ .Values.rest.podMonitor.interval }}
      {{- end }}
      {{- if .Values.rest.podMonitor.path }}
      path: {{ .Values.rest.podMonitor.path }}
      {{- end }}
      {{- if .Values.rest.podMonitor.scheme }}
      scheme: {{ .Values.rest.podMonitor.scheme }}
      {{- end }}
      {{- if .Values.rest.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.rest.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.rest.podMonitor.honorLabels }}
      honorLabels: {{ .Values.rest.podMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.rest.podMonitor.honorTimestamps }}
      honorTimestamps: {{ .Values.rest.podMonitor.honorTimestamps }}
      {{- end }}
      {{- if .Values.rest.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.rest.podMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.rest.podMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.rest.podMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.rest.podMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.rest.podMonitor.tlsConfig | nindent 8 }}
      {{- end }}
  {{- if .Values.rest.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml .Values.rest.podMonitor.podTargetLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.rest.podMonitor.sampleLimit }}
  sampleLimit: {{ .Values.rest.podMonitor.sampleLimit }}
  {{- end }}
  {{- if .Values.rest.podMonitor.targetLimit }}
  targetLimit: {{ .Values.rest.podMonitor.targetLimit }}
  {{- end }}
  {{- if .Values.rest.podMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.rest.podMonitor.namespaceSelector | nindent 4 }}
  {{- end }}
{{- end }}
