{{- if and .Values.rest.enabled (and .Values.rest.rbac (and .Values.rest.rbac .Values.rest.rbac.create) .Values.rest.rbac.create) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rest.rbac.rules | nindent 2 }}
{{- end }}
