{{- if and .Values.rest.enabled .Values.rest.route .Values.rest.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "supabase.fullname" . }}-rest
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
  {{- if .Values.rest.route }}
  {{- with .Values.rest.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.rest.route.host }}
  host: {{ .Values.rest.route.host }}
  {{- end }}
  {{- if .Values.rest.route.subdomain }}
  subdomain: {{ .Values.rest.route.subdomain }}
  {{- end }}
  path: {{ .Values.rest.route.path | default "/rest/v1" }}
  to:
    kind: Service
    name: {{ include "supabase.fullname" . }}-rest
    weight: 100
  port:
    targetPort: {{ .Values.rest.service.targetPort | default "http" }}
  {{- if .Values.rest.route.tls }}
  tls:
    {{- if .Values.rest.route.tls.termination }}
    termination: {{ .Values.rest.route.tls.termination }}
    {{- end }}
    {{- if .Values.rest.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.rest.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if .Values.rest.route.tls.certificate }}
    certificate: |
{{ .Values.rest.route.tls.certificate | indent 6 }}
    {{- end }}
    {{- if .Values.rest.route.tls.key }}
    key: |
{{ .Values.rest.route.tls.key | indent 6 }}
    {{- end }}
    {{- if .Values.rest.route.tls.caCertificate }}
    caCertificate: |
{{ .Values.rest.route.tls.caCertificate | indent 6 }}
    {{- end }}
    {{- if .Values.rest.route.tls.destinationCACertificate }}
    destinationCACertificate: |
{{ .Values.rest.route.tls.destinationCACertificate | indent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.rest.route.wildcardPolicy }}
  wildcardPolicy: {{ .Values.rest.route.wildcardPolicy }}
  {{- end }}
{{- end }}
