{{- if .Values.rest.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-rest
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
type: Opaque
{{- if and .Values.rest.secret .Values.rest.secret.data }}
data:
  {{- toYaml .Values.rest.secret.data | nindent 2 }}
{{- else if and .Values.rest.secret .Values.rest.secret.stringData }}
stringData:
  {{- toYaml .Values.rest.secret.stringData | nindent 2 }}
{{- else }}
stringData:
  database-url: "postgresql://postgres:{{ .Values.legacySecret.db.password }}@{{ include "supabase.database.host" . }}:5432/{{ .Values.legacySecret.db.database }}"
  jwt-secret: {{ .Values.legacySecret.jwt.secret | quote }}
  anon-key: {{ .Values.legacySecret.jwt.anonKey | quote }}
  service-key: {{ .Values.legacySecret.jwt.serviceKey | quote }}
  db-schema: {{ (.Values.rest.config).dbSchema | default "public" | quote }}
  db-anon-role: {{ (.Values.rest.config).dbAnonRole | default "anon" | quote }}
  max-rows: {{ (.Values.rest.config).maxRows | default "1000" | quote }}
{{- end }}
{{- end }}
