{{- if and .Values.meta.enabled (and .Values.meta.rbac .Values.meta.rbac.create) .Values.meta.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "supabase.meta.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.meta.rbac.rules | nindent 2 }}
{{- end }}
